language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.4
    - 8.1
    - 8.2

env:
    - COMPOSER_FLAGS='--prefer-dist'


before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;

install:
    - composer update $COMPOSER_FLAGS
    - bin/simple-phpunit install

script:
    - bin/simple-phpunit -v