name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.4"
        args: --profile --ignore-platform-reqs
    - name: Run unit tests
      uses: php-actions/phpunit@v9